### ISSUE TITLE
Change DNS so that we can use Dan's server

### ISSUE THREAD

**Issue by dantaeyoung** [cybernetics-library/remediation-field#2]
- [x] Get DNS info from Francis
- [x] Setup server (ssh cyberneticslibrary@45.55.191.16)

**Comment by hxrts** [comment]
Transfer just went through. Namecheap prompt says the domain should be active in ~24h.

**Comment by dantaeyoung** [comment]
http://library.cybernetics.social/books should work when the DNS propages
